name: turinova-erp
services:
  - name: erp-app
    source_dir: .
    github:
      repo: turinova/turinova-project
      branch: main
    run_command: php -S 0.0.0.0:8080 -t erp-app/public/
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: ${db.DATABASE_HOST}
      - key: DB_NAME
        value: ${db.DATABASE_NAME}
      - key: DB_USER
        value: ${db.DATABASE_USERNAME}
      - key: DB_PASS
        value: ${db.DATABASE_PASSWORD}
      - key: DB_CHARSET
        value: utf8mb4

databases:
  - name: turinova-master
    engine: mysql
    version: "8"
    size: db-s-1vcpu-1gb
    num_nodes: 1
    db_name: turinova_master
    db_user: turinova_admin
