name: turinova-erp
services:
  - name: erp-app
    source_dir: .
    github:
      repo: turinova/turinova-project
      branch: main
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: APP_ENV
        value: production
      - key: DB_TYPE
        value: pgsql
      - key: DB_HOST
        value: ${db.DATABASE_HOST}
      - key: DB_PORT
        value: ${db.DATABASE_PORT}
      - key: DB_NAME
        value: ${db.DATABASE_NAME}
      - key: DB_USER
        value: ${db.DATABASE_USERNAME}
      - key: DB_PASS
        value: ${db.DATABASE_PASSWORD}
      - key: DB_CHARSET
        value: utf8

databases:
  - name: db-postgresql-fra1-89553
    engine: pg
    version: "15"
    size: db-s-1vcpu-1gb
    num_nodes: 1
    db_name: defaultdb
    db_user: doadmin
